# fly.toml app configuration file generated for winter-hill-6060 on 2023-08-11T16:46:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "winter-hill-6060"
primary_region = "atl"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
